Implement post-quantum block level access control
Peergos/Peergos pull request #884
Opened 2021-12-31 09:58 UTC by ianopolous

This adds a capability based scheme for authorising retrieval of a block. To retrieve a block you need a Block Access Token (BAT) which is 32 random bytes. To retrieve a block you use an applicable BAT to generate an S3 V4 signature and include that in the request over bitswap (or send the BAT directly to the Peergos API).

Cryptree nodes store a list of BATs under the cbor key "bats" in the top level. They also store a nested BAT for each linked raw fragment. Each user has a mirror BAT which can be used to mirror their entire block set. A node can also have a node wide BAT which can be used to retrieve any block on the instance.

2021-12-31 12:24 UTC, kevodwyer requested changes
I didn't mark all the places with the word Cave. I would suggest dropping it.

2021-12-31 12:24 UTC, kevodwyer commented on src/peergos/server/storage/S3BlockStorage.java
> +        // retrieve all blocks and verify BATs in aprallel
spelling of parallel

2021-12-31 12:24 UTC, kevodwyer commented on src/peergos/shared/storage/auth/Bat.java
> +        // TODO need to analyse the cryptographic properties of this construction, might need to use hmac_sha256 instead
this still a todo?

2022-01-02 02:29 UTC, ianopolous commented on src/peergos/shared/storage/auth/Bat.java
> +        // TODO need to analyse the cryptographic properties of this construction, might need to use hmac_sha256 instead
yep.

2022-01-02 17:51 UTC, ianopolous commented on src/peergos/server/Main.java
> +            BatWithId current = mirrorBats.get(mirrorBats.size() - 1);
done

2022-01-10 16:11 UTC, kevodwyer approved these changes

2022-01-12 23:47 UTC, merged